name: fake_ui
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

#----------------PACKAGES ----------------
dependencies:
  flutter:
    sdk: flutter

    # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

   # State Managements
  get: ^4.6.6

  # Products Specific

#---------------- ./ PACKAGES END----------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Local assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  # Local fonts:
  fonts:
    - family: Nunito_Sans
      fonts:
        - asset: assets/fonts/nunitosans_light.ttf
          weight: 300
        - asset: assets/fonts/nunitosans_light.ttf
          weight: 400
        - asset: assets/fonts/nunitosans_light.ttf
          weight: 500
        - asset: assets/fonts/nunitosans_bold.ttf
          weight: 600
        - asset: assets/fonts/nunitosans_semibold.ttf
          weight: 800

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

